// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Linq;

namespace Pulumi.Azure.Dns {

	public sealed class MxRecordArgsRecord : Pulumi.IIOProtobuf {
		public Pulumi.IO<string> Exchange { get; set; }
		public Pulumi.IO<string> Preference { get; set; }

		public Pulumi.IO<Google.Protobuf.WellKnownTypes.Value> ToProtobuf() {
			return Protobuf.ToProtobuf(
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("exchange", Protobuf.ToProtobuf(Exchange)),
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("preference", Protobuf.ToProtobuf(Preference)));
		} // ToProtobuf

	} // MxRecordArgsRecord

	public sealed class MxRecordRecord : Pulumi.IIOProtobuf {
		public Pulumi.IO<string> Exchange { get; set; }
		public Pulumi.IO<string> Preference { get; set; }

		public Pulumi.IO<Google.Protobuf.WellKnownTypes.Value> ToProtobuf() {
			return Protobuf.ToProtobuf(
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("exchange", Protobuf.ToProtobuf(Exchange)),
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("preference", Protobuf.ToProtobuf(Preference)));
		} // ToProtobuf

		public static MxRecordRecord FromProtobuf(Google.Protobuf.WellKnownTypes.Value value) {
			var obj = value.StructValue;
			var result = new MxRecordRecord();
				if (obj.Fields.ContainsKey("exchange")) {
					result.Exchange = Protobuf.ToString(obj.Fields["exchange"]);
				}
				if (obj.Fields.ContainsKey("preference")) {
					result.Preference = Protobuf.ToString(obj.Fields["preference"]);
				}
			return result;
		} // FromProtobuf

	} // MxRecordRecord

	/// <summary>
	/// The set of arguments for constructing a MxRecord resource.
	/// </summary>
	public struct MxRecordArgs {
		/// <summary>
		/// The name of the DNS MX Record.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// A list of values that make up the MX record. Each `record` block supports fields documented below.
		/// </summary>
		public Pulumi.IO<Pulumi.IO<MxRecordArgsRecord>[]> Records { get; set; }

		/// <summary>
		/// Specifies the resource group where the resource exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// A mapping of tags to assign to the resource.
		/// </summary>
		public Pulumi.IO<System.Collections.Generic.Dictionary<string, string>> Tags { get; set; }

		/// <summary>
		/// The Time To Live (TTL) of the DNS record in seconds.
		/// </summary>
		public Pulumi.IO<int> Ttl { get; set; }

		/// <summary>
		/// Specifies the DNS Zone where the resource exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ZoneName { get; set; }

	} // MxRecordArgs

	/// <summary>
	/// Enables you to manage DNS MX Records within Azure DNS.
	/// </summary>
	public class MxRecord : Pulumi.CustomResource {
		/// <summary>
		/// The name of the DNS MX Record.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// A list of values that make up the MX record. Each `record` block supports fields documented below.
		/// </summary>
		public Pulumi.IO<MxRecordRecord[]> Records { get; set; }

		/// <summary>
		/// Specifies the resource group where the resource exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// A mapping of tags to assign to the resource.
		/// </summary>
		public Pulumi.IO<System.Collections.Generic.Dictionary<string, string>> Tags { get; set; }

		/// <summary>
		/// The Time To Live (TTL) of the DNS record in seconds.
		/// </summary>
		public Pulumi.IO<int> Ttl { get; set; }

		/// <summary>
		/// Specifies the DNS Zone where the resource exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ZoneName { get; set; }

		public MxRecord(string name, MxRecordArgs args, Pulumi.ResourceOptions opts = default(Pulumi.ResourceOptions))
			: base("azure:dns/mxRecord:MxRecord", name, SerialiseArgs(args), opts) {
			Name = base.Outputs["name"].Select(item => Protobuf.ToString(item));
			Records = base.Outputs["records"].Select(item => Protobuf.ToList(item, item1 => MxRecordRecord.FromProtobuf(item1)));
			ResourceGroupName = base.Outputs["resourceGroupName"].Select(item => Protobuf.ToString(item));
			Tags = base.Outputs["tags"].Select(item => Protobuf.ToMap(item));
			Ttl = base.Outputs["ttl"].Select(item => Protobuf.ToInt(item));
			ZoneName = base.Outputs["zoneName"].Select(item => Protobuf.ToString(item));
		} // ctor

		private static Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>> SerialiseArgs(MxRecordArgs args) {
			var props = new Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>();
			props["name"] = Protobuf.ToProtobuf(args.Name);
			props["records"] = Protobuf.ToProtobuf(args.Records, item => Protobuf.ToProtobuf(item));
			props["resourceGroupName"] = Protobuf.ToProtobuf(args.ResourceGroupName);
			props["tags"] = Protobuf.ToProtobuf(args.Tags);
			props["ttl"] = Protobuf.ToProtobuf(args.Ttl);
			props["zoneName"] = Protobuf.ToProtobuf(args.ZoneName);
			return props;
		} // SerialiseArgs

	} // MxRecord
} // Pulumi.Azure.Dns
