// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Linq;

namespace Pulumi.Azure.Dns {

	public sealed class SrvRecordArgsRecord : Pulumi.IIOProtobuf {
		public Pulumi.IO<int> Port { get; set; }
		public Pulumi.IO<int> Priority { get; set; }
		public Pulumi.IO<string> Target { get; set; }
		public Pulumi.IO<int> Weight { get; set; }

		public Pulumi.IO<Google.Protobuf.WellKnownTypes.Value> ToProtobuf() {
			return Protobuf.ToProtobuf(
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("port", Protobuf.ToProtobuf(Port)),
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("priority", Protobuf.ToProtobuf(Priority)),
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("target", Protobuf.ToProtobuf(Target)),
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("weight", Protobuf.ToProtobuf(Weight)));
		} // ToProtobuf

	} // SrvRecordArgsRecord

	public sealed class SrvRecordRecord : Pulumi.IIOProtobuf {
		public Pulumi.IO<int> Port { get; set; }
		public Pulumi.IO<int> Priority { get; set; }
		public Pulumi.IO<string> Target { get; set; }
		public Pulumi.IO<int> Weight { get; set; }

		public Pulumi.IO<Google.Protobuf.WellKnownTypes.Value> ToProtobuf() {
			return Protobuf.ToProtobuf(
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("port", Protobuf.ToProtobuf(Port)),
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("priority", Protobuf.ToProtobuf(Priority)),
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("target", Protobuf.ToProtobuf(Target)),
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("weight", Protobuf.ToProtobuf(Weight)));
		} // ToProtobuf

		public static SrvRecordRecord FromProtobuf(Google.Protobuf.WellKnownTypes.Value value) {
			var obj = value.StructValue;
			var result = new SrvRecordRecord();
				if (obj.Fields.ContainsKey("port")) {
					result.Port = Protobuf.ToInt(obj.Fields["port"]);
				}
				if (obj.Fields.ContainsKey("priority")) {
					result.Priority = Protobuf.ToInt(obj.Fields["priority"]);
				}
				if (obj.Fields.ContainsKey("target")) {
					result.Target = Protobuf.ToString(obj.Fields["target"]);
				}
				if (obj.Fields.ContainsKey("weight")) {
					result.Weight = Protobuf.ToInt(obj.Fields["weight"]);
				}
			return result;
		} // FromProtobuf

	} // SrvRecordRecord

	/// <summary>
	/// The set of arguments for constructing a SrvRecord resource.
	/// </summary>
	public struct SrvRecordArgs {
		/// <summary>
		/// The name of the DNS SRV Record.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// A list of values that make up the SRV record. Each `record` block supports fields documented below.
		/// </summary>
		public Pulumi.IO<Pulumi.IO<SrvRecordArgsRecord>[]> Records { get; set; }

		/// <summary>
		/// Specifies the resource group where the resource exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// A mapping of tags to assign to the resource.
		/// </summary>
		public Pulumi.IO<System.Collections.Generic.Dictionary<string, string>> Tags { get; set; }

		/// <summary>
		/// The Time To Live (TTL) of the DNS record in seconds.
		/// </summary>
		public Pulumi.IO<int> Ttl { get; set; }

		/// <summary>
		/// Specifies the DNS Zone where the resource exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ZoneName { get; set; }

	} // SrvRecordArgs

	/// <summary>
	/// Enables you to manage DNS SRV Records within Azure DNS.
	/// </summary>
	public class SrvRecord : Pulumi.CustomResource {
		/// <summary>
		/// The name of the DNS SRV Record.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// A list of values that make up the SRV record. Each `record` block supports fields documented below.
		/// </summary>
		public Pulumi.IO<SrvRecordRecord[]> Records { get; set; }

		/// <summary>
		/// Specifies the resource group where the resource exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// A mapping of tags to assign to the resource.
		/// </summary>
		public Pulumi.IO<System.Collections.Generic.Dictionary<string, string>> Tags { get; set; }

		/// <summary>
		/// The Time To Live (TTL) of the DNS record in seconds.
		/// </summary>
		public Pulumi.IO<int> Ttl { get; set; }

		/// <summary>
		/// Specifies the DNS Zone where the resource exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ZoneName { get; set; }

		public SrvRecord(string name, SrvRecordArgs args, Pulumi.ResourceOptions opts = default(Pulumi.ResourceOptions))
			: base("azure:dns/srvRecord:SrvRecord", name, SerialiseArgs(args), opts) {
			Name = base.Outputs["name"].Select(item => Protobuf.ToString(item));
			Records = base.Outputs["records"].Select(item => Protobuf.ToList(item, item1 => SrvRecordRecord.FromProtobuf(item1)));
			ResourceGroupName = base.Outputs["resourceGroupName"].Select(item => Protobuf.ToString(item));
			Tags = base.Outputs["tags"].Select(item => Protobuf.ToMap(item));
			Ttl = base.Outputs["ttl"].Select(item => Protobuf.ToInt(item));
			ZoneName = base.Outputs["zoneName"].Select(item => Protobuf.ToString(item));
		} // ctor

		private static Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>> SerialiseArgs(SrvRecordArgs args) {
			var props = new Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>();
			props["name"] = Protobuf.ToProtobuf(args.Name);
			props["records"] = Protobuf.ToProtobuf(args.Records, item => Protobuf.ToProtobuf(item));
			props["resourceGroupName"] = Protobuf.ToProtobuf(args.ResourceGroupName);
			props["tags"] = Protobuf.ToProtobuf(args.Tags);
			props["ttl"] = Protobuf.ToProtobuf(args.Ttl);
			props["zoneName"] = Protobuf.ToProtobuf(args.ZoneName);
			return props;
		} // SerialiseArgs

	} // SrvRecord
} // Pulumi.Azure.Dns
