// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Service extends pulumi.CustomResource {
    /**
     * Get an existing Service resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceState, opts?: pulumi.CustomResourceOptions): Service {
        return new Service(name, <any>state, { ...opts, id: id });
    }

    public readonly agentPoolProfile: pulumi.Output<{ count?: number, dnsPrefix: string, fqdn: string, name: string, vmSize: string }>;
    public readonly diagnosticsProfile: pulumi.Output<{ enabled: boolean, storageUri: string }>;
    public readonly linuxProfile: pulumi.Output<{ adminUsername: string, sshKey: { keyData: string } }>;
    public readonly location: pulumi.Output<string>;
    public readonly masterProfile: pulumi.Output<{ count?: number, dnsPrefix: string, fqdn: string }>;
    public readonly name: pulumi.Output<string>;
    public readonly orchestrationPlatform: pulumi.Output<string>;
    public readonly resourceGroupName: pulumi.Output<string>;
    public readonly servicePrincipal: pulumi.Output<{ clientId: string, clientSecret: string } | undefined>;
    public readonly tags: pulumi.Output<{[key: string]: any}>;

    /**
     * Create a Service resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceArgs | ServiceState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: ServiceState = argsOrState as ServiceState | undefined;
            inputs["agentPoolProfile"] = state ? state.agentPoolProfile : undefined;
            inputs["diagnosticsProfile"] = state ? state.diagnosticsProfile : undefined;
            inputs["linuxProfile"] = state ? state.linuxProfile : undefined;
            inputs["location"] = state ? state.location : undefined;
            inputs["masterProfile"] = state ? state.masterProfile : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["orchestrationPlatform"] = state ? state.orchestrationPlatform : undefined;
            inputs["resourceGroupName"] = state ? state.resourceGroupName : undefined;
            inputs["servicePrincipal"] = state ? state.servicePrincipal : undefined;
            inputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as ServiceArgs | undefined;
            if (!args || args.agentPoolProfile === undefined) {
                throw new Error("Missing required property 'agentPoolProfile'");
            }
            if (!args || args.diagnosticsProfile === undefined) {
                throw new Error("Missing required property 'diagnosticsProfile'");
            }
            if (!args || args.linuxProfile === undefined) {
                throw new Error("Missing required property 'linuxProfile'");
            }
            if (!args || args.location === undefined) {
                throw new Error("Missing required property 'location'");
            }
            if (!args || args.masterProfile === undefined) {
                throw new Error("Missing required property 'masterProfile'");
            }
            if (!args || args.orchestrationPlatform === undefined) {
                throw new Error("Missing required property 'orchestrationPlatform'");
            }
            if (!args || args.resourceGroupName === undefined) {
                throw new Error("Missing required property 'resourceGroupName'");
            }
            inputs["agentPoolProfile"] = args ? args.agentPoolProfile : undefined;
            inputs["diagnosticsProfile"] = args ? args.diagnosticsProfile : undefined;
            inputs["linuxProfile"] = args ? args.linuxProfile : undefined;
            inputs["location"] = args ? args.location : undefined;
            inputs["masterProfile"] = args ? args.masterProfile : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["orchestrationPlatform"] = args ? args.orchestrationPlatform : undefined;
            inputs["resourceGroupName"] = args ? args.resourceGroupName : undefined;
            inputs["servicePrincipal"] = args ? args.servicePrincipal : undefined;
            inputs["tags"] = args ? args.tags : undefined;
        }
        super("azure:containerservice/service:Service", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Service resources.
 */
export interface ServiceState {
    readonly agentPoolProfile?: pulumi.Input<{ count?: pulumi.Input<number>, dnsPrefix: pulumi.Input<string>, fqdn?: pulumi.Input<string>, name: pulumi.Input<string>, vmSize: pulumi.Input<string> }>;
    readonly diagnosticsProfile?: pulumi.Input<{ enabled: pulumi.Input<boolean>, storageUri?: pulumi.Input<string> }>;
    readonly linuxProfile?: pulumi.Input<{ adminUsername: pulumi.Input<string>, sshKey: pulumi.Input<{ keyData: pulumi.Input<string> }> }>;
    readonly location?: pulumi.Input<string>;
    readonly masterProfile?: pulumi.Input<{ count?: pulumi.Input<number>, dnsPrefix: pulumi.Input<string>, fqdn?: pulumi.Input<string> }>;
    readonly name?: pulumi.Input<string>;
    readonly orchestrationPlatform?: pulumi.Input<string>;
    readonly resourceGroupName?: pulumi.Input<string>;
    readonly servicePrincipal?: pulumi.Input<{ clientId: pulumi.Input<string>, clientSecret: pulumi.Input<string> }>;
    readonly tags?: pulumi.Input<{[key: string]: any}>;
}

/**
 * The set of arguments for constructing a Service resource.
 */
export interface ServiceArgs {
    readonly agentPoolProfile: pulumi.Input<{ count?: pulumi.Input<number>, dnsPrefix: pulumi.Input<string>, fqdn?: pulumi.Input<string>, name: pulumi.Input<string>, vmSize: pulumi.Input<string> }>;
    readonly diagnosticsProfile: pulumi.Input<{ enabled: pulumi.Input<boolean>, storageUri?: pulumi.Input<string> }>;
    readonly linuxProfile: pulumi.Input<{ adminUsername: pulumi.Input<string>, sshKey: pulumi.Input<{ keyData: pulumi.Input<string> }> }>;
    readonly location: pulumi.Input<string>;
    readonly masterProfile: pulumi.Input<{ count?: pulumi.Input<number>, dnsPrefix: pulumi.Input<string>, fqdn?: pulumi.Input<string> }>;
    readonly name?: pulumi.Input<string>;
    readonly orchestrationPlatform: pulumi.Input<string>;
    readonly resourceGroupName: pulumi.Input<string>;
    readonly servicePrincipal?: pulumi.Input<{ clientId: pulumi.Input<string>, clientSecret: pulumi.Input<string> }>;
    readonly tags?: pulumi.Input<{[key: string]: any}>;
}
