[[constraint]]
  name = "github.com/pulumi/pulumi"
  branch = "master"

[[constraint]]
  name = "github.com/pulumi/pulumi-terraform"
  branch = "master"

[[constraint]]
  branch = "pulumi-master"
  name = "github.com/terraform-providers/terraform-provider-azurerm"
  source = "github.com/pulumi/terraform-provider-azurerm"

  [constraint.metadata]
    govendor-override = true
