// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class TriggerRecurrence extends pulumi.CustomResource {
    /**
     * Get an existing TriggerRecurrence resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TriggerRecurrenceState, opts?: pulumi.CustomResourceOptions): TriggerRecurrence {
        return new TriggerRecurrence(name, <any>state, { ...opts, id: id });
    }

    public readonly frequency: pulumi.Output<string>;
    public readonly interval: pulumi.Output<number>;
    public readonly logicAppId: pulumi.Output<string>;
    public readonly name: pulumi.Output<string>;

    /**
     * Create a TriggerRecurrence resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TriggerRecurrenceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TriggerRecurrenceArgs | TriggerRecurrenceState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: TriggerRecurrenceState = argsOrState as TriggerRecurrenceState | undefined;
            inputs["frequency"] = state ? state.frequency : undefined;
            inputs["interval"] = state ? state.interval : undefined;
            inputs["logicAppId"] = state ? state.logicAppId : undefined;
            inputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as TriggerRecurrenceArgs | undefined;
            if (!args || args.frequency === undefined) {
                throw new Error("Missing required property 'frequency'");
            }
            if (!args || args.interval === undefined) {
                throw new Error("Missing required property 'interval'");
            }
            if (!args || args.logicAppId === undefined) {
                throw new Error("Missing required property 'logicAppId'");
            }
            inputs["frequency"] = args ? args.frequency : undefined;
            inputs["interval"] = args ? args.interval : undefined;
            inputs["logicAppId"] = args ? args.logicAppId : undefined;
            inputs["name"] = args ? args.name : undefined;
        }
        super("azure:logicapps/triggerRecurrence:TriggerRecurrence", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TriggerRecurrence resources.
 */
export interface TriggerRecurrenceState {
    readonly frequency?: pulumi.Input<string>;
    readonly interval?: pulumi.Input<number>;
    readonly logicAppId?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a TriggerRecurrence resource.
 */
export interface TriggerRecurrenceArgs {
    readonly frequency: pulumi.Input<string>;
    readonly interval: pulumi.Input<number>;
    readonly logicAppId: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
}
