// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Linq;

namespace Pulumi.Azure.Redis {

	/// <summary>
	/// The set of arguments for constructing a FirewallRule resource.
	/// </summary>
	public struct FirewallRuleArgs {
		/// <summary>
		/// The highest IP address included in the range.
		/// </summary>
		public Pulumi.IO<string> EndIp { get; set; }

		/// <summary>
		/// The name of the Firewall Rule. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// The name of the Redis Cache. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> RedisCacheName { get; set; }

		/// <summary>
		/// The name of the resource group in which this Redis Cache exists.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// The lowest IP address included in the range
		/// </summary>
		public Pulumi.IO<string> StartIp { get; set; }

	} // FirewallRuleArgs

	/// <summary>
	/// Manages a Firewall Rule associated with a Redis Cache.
	/// </summary>
	public class FirewallRule : Pulumi.CustomResource {
		/// <summary>
		/// The highest IP address included in the range.
		/// </summary>
		public Pulumi.IO<string> EndIp { get; set; }

		/// <summary>
		/// The name of the Firewall Rule. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// The name of the Redis Cache. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> RedisCacheName { get; set; }

		/// <summary>
		/// The name of the resource group in which this Redis Cache exists.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// The lowest IP address included in the range
		/// </summary>
		public Pulumi.IO<string> StartIp { get; set; }

		public FirewallRule(string name, FirewallRuleArgs args, Pulumi.ResourceOptions opts = default(Pulumi.ResourceOptions))
			: base("azure:redis/firewallRule:FirewallRule", name, SerialiseArgs(args), opts) {
			EndIp = base.Outputs["endIp"].Select(item => Protobuf.ToString(item));
			Name = base.Outputs["name"].Select(item => Protobuf.ToString(item));
			RedisCacheName = base.Outputs["redisCacheName"].Select(item => Protobuf.ToString(item));
			ResourceGroupName = base.Outputs["resourceGroupName"].Select(item => Protobuf.ToString(item));
			StartIp = base.Outputs["startIp"].Select(item => Protobuf.ToString(item));
		} // ctor

		private static Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>> SerialiseArgs(FirewallRuleArgs args) {
			var props = new Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>();
			props["endIp"] = Protobuf.ToProtobuf(args.EndIp);
			props["name"] = Protobuf.ToProtobuf(args.Name);
			props["redisCacheName"] = Protobuf.ToProtobuf(args.RedisCacheName);
			props["resourceGroupName"] = Protobuf.ToProtobuf(args.ResourceGroupName);
			props["startIp"] = Protobuf.ToProtobuf(args.StartIp);
			return props;
		} // SerialiseArgs

	} // FirewallRule
} // Pulumi.Azure.Redis
