// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Linq;

namespace Pulumi.Azure.Network {

	public sealed class GetNetworkSecurityGroupSecurityRule : Pulumi.IProtobuf {
		public string Access { get; set; }
		public string Description { get; set; }
		public string DestinationAddressPrefix { get; set; }
		public string[] DestinationAddressPrefixes { get; set; }
		public string[] DestinationApplicationSecurityGroupIds { get; set; }
		public string DestinationPortRange { get; set; }
		public string[] DestinationPortRanges { get; set; }
		public string Direction { get; set; }
		public string Name { get; set; }
		public int Priority { get; set; }
		public string Protocol { get; set; }
		public string SourceAddressPrefix { get; set; }
		public string[] SourceAddressPrefixes { get; set; }
		public string[] SourceApplicationSecurityGroupIds { get; set; }
		public string SourcePortRange { get; set; }
		public string[] SourcePortRanges { get; set; }

		public Google.Protobuf.WellKnownTypes.Value ToProtobuf() {
			return Protobuf.ToProtobuf(
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("access", Protobuf.ToProtobuf(Access)),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("description", Protobuf.ToProtobuf(Description)),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("destination_address_prefix", Protobuf.ToProtobuf(DestinationAddressPrefix)),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("destination_address_prefixes", Protobuf.ToProtobuf(DestinationAddressPrefixes, item => Protobuf.ToProtobuf(item))),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("destination_application_security_group_ids", Protobuf.ToProtobuf(DestinationApplicationSecurityGroupIds, item => Protobuf.ToProtobuf(item))),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("destination_port_range", Protobuf.ToProtobuf(DestinationPortRange)),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("destination_port_ranges", Protobuf.ToProtobuf(DestinationPortRanges, item => Protobuf.ToProtobuf(item))),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("direction", Protobuf.ToProtobuf(Direction)),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("name", Protobuf.ToProtobuf(Name)),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("priority", Protobuf.ToProtobuf(Priority)),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("protocol", Protobuf.ToProtobuf(Protocol)),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("source_address_prefix", Protobuf.ToProtobuf(SourceAddressPrefix)),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("source_address_prefixes", Protobuf.ToProtobuf(SourceAddressPrefixes, item => Protobuf.ToProtobuf(item))),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("source_application_security_group_ids", Protobuf.ToProtobuf(SourceApplicationSecurityGroupIds, item => Protobuf.ToProtobuf(item))),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("source_port_range", Protobuf.ToProtobuf(SourcePortRange)),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("source_port_ranges", Protobuf.ToProtobuf(SourcePortRanges, item => Protobuf.ToProtobuf(item))));
		} // ToProtobuf

		public static GetNetworkSecurityGroupSecurityRule FromProtobuf(Google.Protobuf.WellKnownTypes.Value value) {
			var obj = value.StructValue;
			var result = new GetNetworkSecurityGroupSecurityRule();
				if (obj.Fields.ContainsKey("access")) {
					result.Access = Protobuf.ToString(obj.Fields["access"]);
				}
				if (obj.Fields.ContainsKey("description")) {
					result.Description = Protobuf.ToString(obj.Fields["description"]);
				}
				if (obj.Fields.ContainsKey("destination_address_prefix")) {
					result.DestinationAddressPrefix = Protobuf.ToString(obj.Fields["destination_address_prefix"]);
				}
				if (obj.Fields.ContainsKey("destination_address_prefixes")) {
					result.DestinationAddressPrefixes = Protobuf.ToList(obj.Fields["destination_address_prefixes"], item => Protobuf.ToString(item));
				}
				if (obj.Fields.ContainsKey("destination_application_security_group_ids")) {
					result.DestinationApplicationSecurityGroupIds = Protobuf.ToList(obj.Fields["destination_application_security_group_ids"], item => Protobuf.ToString(item));
				}
				if (obj.Fields.ContainsKey("destination_port_range")) {
					result.DestinationPortRange = Protobuf.ToString(obj.Fields["destination_port_range"]);
				}
				if (obj.Fields.ContainsKey("destination_port_ranges")) {
					result.DestinationPortRanges = Protobuf.ToList(obj.Fields["destination_port_ranges"], item => Protobuf.ToString(item));
				}
				if (obj.Fields.ContainsKey("direction")) {
					result.Direction = Protobuf.ToString(obj.Fields["direction"]);
				}
				if (obj.Fields.ContainsKey("name")) {
					result.Name = Protobuf.ToString(obj.Fields["name"]);
				}
				if (obj.Fields.ContainsKey("priority")) {
					result.Priority = Protobuf.ToInt(obj.Fields["priority"]);
				}
				if (obj.Fields.ContainsKey("protocol")) {
					result.Protocol = Protobuf.ToString(obj.Fields["protocol"]);
				}
				if (obj.Fields.ContainsKey("source_address_prefix")) {
					result.SourceAddressPrefix = Protobuf.ToString(obj.Fields["source_address_prefix"]);
				}
				if (obj.Fields.ContainsKey("source_address_prefixes")) {
					result.SourceAddressPrefixes = Protobuf.ToList(obj.Fields["source_address_prefixes"], item => Protobuf.ToString(item));
				}
				if (obj.Fields.ContainsKey("source_application_security_group_ids")) {
					result.SourceApplicationSecurityGroupIds = Protobuf.ToList(obj.Fields["source_application_security_group_ids"], item => Protobuf.ToString(item));
				}
				if (obj.Fields.ContainsKey("source_port_range")) {
					result.SourcePortRange = Protobuf.ToString(obj.Fields["source_port_range"]);
				}
				if (obj.Fields.ContainsKey("source_port_ranges")) {
					result.SourcePortRanges = Protobuf.ToList(obj.Fields["source_port_ranges"], item => Protobuf.ToString(item));
				}
			return result;
		} // FromProtobuf

	} // GetNetworkSecurityGroupSecurityRule

	/// <summary>
	/// A collection of arguments for invoking getNetworkSecurityGroup.
	/// </summary>
	public struct GetNetworkSecurityGroupArgs {
		/// <summary>
		/// Specifies the Name of the Network Security Group.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// Specifies the Name of the Resource Group within which the Network Security Group exists
		/// </summary>
		public string ResourceGroupName { get; set; }

	} // GetNetworkSecurityGroupArgs

	/// <summary>
	/// A collection of values returned by getNetworkSecurityGroup.
	/// </summary>
	public struct GetNetworkSecurityGroupResult {
		/// <summary>
		/// The supported Azure location where the resource exists.
		/// </summary>
		public string Location { get; set; }

		/// <summary>
		/// One or more `security_rule` blocks as defined below.
		/// </summary>
		public GetNetworkSecurityGroupSecurityRule[] SecurityRules { get; set; }

		/// <summary>
		/// A mapping of tags assigned to the resource.
		/// </summary>
		public System.Collections.Generic.Dictionary<string, string> Tags { get; set; }

		/// <summary>
		/// id is the provider-assigned unique ID for this managed resource.
		/// </summary>
		public string Id { get; set; }

	} // GetNetworkSecurityGroupResult

	public static partial class NetworkModule {
		/// <summary>
		/// Use this data source to access information about an existing Network Security Group.
		/// </summary>
		public static System.Threading.Tasks.Task<GetNetworkSecurityGroupResult> GetNetworkSecurityGroup(GetNetworkSecurityGroupArgs args, Pulumi.InvokeOptions opts = default(Pulumi.InvokeOptions)) {
			var invokeArgs = new Google.Protobuf.WellKnownTypes.Struct();
			invokeArgs.Fields["name"] = Protobuf.ToProtobuf(args.Name);
			invokeArgs.Fields["resourceGroupName"] = Protobuf.ToProtobuf(args.ResourceGroupName);

			var task = Pulumi.Runtime.InvokeAsync("azure:network/getNetworkSecurityGroup:getNetworkSecurityGroup", invokeArgs, opts);

			return task.ContinueWith(response => {
				var protobuf = response.Result;
				var result = new GetNetworkSecurityGroupResult();
				if (protobuf.Fields.ContainsKey("location")) {
					result.Location = Protobuf.ToString(protobuf.Fields["location"]);
				}
				if (protobuf.Fields.ContainsKey("securityRules")) {
					result.SecurityRules = Protobuf.ToList(protobuf.Fields["securityRules"], item => GetNetworkSecurityGroupSecurityRule.FromProtobuf(item));
				}
				if (protobuf.Fields.ContainsKey("tags")) {
					result.Tags = Protobuf.ToMap(protobuf.Fields["tags"]);
				}
				if (protobuf.Fields.ContainsKey("id")) {
					result.Id = Protobuf.ToString(protobuf.Fields["id"]);
				}
				return result;
			});
		} // GetNetworkSecurityGroup

	} // NetworkModule
} // Pulumi.Azure.Network
