// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Linq;

namespace Pulumi.Azure.Network {

	public sealed class LocalNetworkGatewayArgsBgpSetting : Pulumi.IIOProtobuf {
		public Pulumi.IO<int> Asn { get; set; }
		public Pulumi.IO<string> BgpPeeringAddress { get; set; }
		public Pulumi.IO<int> PeerWeight { get; set; }

		public Pulumi.IO<Google.Protobuf.WellKnownTypes.Value> ToProtobuf() {
			return Protobuf.ToProtobuf(
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("asn", Protobuf.ToProtobuf(Asn)),
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("bgp_peering_address", Protobuf.ToProtobuf(BgpPeeringAddress)),
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("peer_weight", Protobuf.ToProtobuf(PeerWeight)));
		} // ToProtobuf

	} // LocalNetworkGatewayArgsBgpSetting

	public sealed class LocalNetworkGatewayBgpSetting : Pulumi.IIOProtobuf {
		public Pulumi.IO<int> Asn { get; set; }
		public Pulumi.IO<string> BgpPeeringAddress { get; set; }
		public Pulumi.IO<int> PeerWeight { get; set; }

		public Pulumi.IO<Google.Protobuf.WellKnownTypes.Value> ToProtobuf() {
			return Protobuf.ToProtobuf(
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("asn", Protobuf.ToProtobuf(Asn)),
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("bgp_peering_address", Protobuf.ToProtobuf(BgpPeeringAddress)),
				new KeyValuePair<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>("peer_weight", Protobuf.ToProtobuf(PeerWeight)));
		} // ToProtobuf

		public static LocalNetworkGatewayBgpSetting FromProtobuf(Google.Protobuf.WellKnownTypes.Value value) {
			var obj = value.StructValue;
			var result = new LocalNetworkGatewayBgpSetting();
				if (obj.Fields.ContainsKey("asn")) {
					result.Asn = Protobuf.ToInt(obj.Fields["asn"]);
				}
				if (obj.Fields.ContainsKey("bgp_peering_address")) {
					result.BgpPeeringAddress = Protobuf.ToString(obj.Fields["bgp_peering_address"]);
				}
				if (obj.Fields.ContainsKey("peer_weight")) {
					result.PeerWeight = Protobuf.ToInt(obj.Fields["peer_weight"]);
				}
			return result;
		} // FromProtobuf

	} // LocalNetworkGatewayBgpSetting

	/// <summary>
	/// The set of arguments for constructing a LocalNetworkGateway resource.
	/// </summary>
	public struct LocalNetworkGatewayArgs {
		/// <summary>
		/// The list of string CIDRs representing the
		/// address spaces the gateway exposes.
		/// </summary>
		public Pulumi.IO<Pulumi.IO<string>[]> AddressSpaces { get; set; }

		/// <summary>
		/// A `bgp_settings` block as defined below containing the
		/// Local Network Gateway's BGP speaker settings.
		/// </summary>
		public Pulumi.IO<LocalNetworkGatewayArgsBgpSetting> BgpSettings { get; set; }

		/// <summary>
		/// The IP address of the gateway to which to
		/// connect.
		/// </summary>
		public Pulumi.IO<string> GatewayAddress { get; set; }

		/// <summary>
		/// The location/region where the local network gateway is
		/// created. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Location { get; set; }

		/// <summary>
		/// The name of the local network gateway. Changing this
		/// forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// The name of the resource group in which to
		/// create the local network gateway.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// A mapping of tags to assign to the resource.
		/// </summary>
		public Pulumi.IO<System.Collections.Generic.Dictionary<string, string>> Tags { get; set; }

	} // LocalNetworkGatewayArgs

	/// <summary>
	/// Manages a local network gateway connection over which specific connections can be configured.
	/// </summary>
	public class LocalNetworkGateway : Pulumi.CustomResource {
		/// <summary>
		/// The list of string CIDRs representing the
		/// address spaces the gateway exposes.
		/// </summary>
		public Pulumi.IO<string[]> AddressSpaces { get; set; }

		/// <summary>
		/// A `bgp_settings` block as defined below containing the
		/// Local Network Gateway's BGP speaker settings.
		/// </summary>
		public Pulumi.IO<LocalNetworkGatewayBgpSetting> BgpSettings { get; set; }

		/// <summary>
		/// The IP address of the gateway to which to
		/// connect.
		/// </summary>
		public Pulumi.IO<string> GatewayAddress { get; set; }

		/// <summary>
		/// The location/region where the local network gateway is
		/// created. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Location { get; set; }

		/// <summary>
		/// The name of the local network gateway. Changing this
		/// forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// The name of the resource group in which to
		/// create the local network gateway.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// A mapping of tags to assign to the resource.
		/// </summary>
		public Pulumi.IO<System.Collections.Generic.Dictionary<string, string>> Tags { get; set; }

		public LocalNetworkGateway(string name, LocalNetworkGatewayArgs args, Pulumi.ResourceOptions opts = default(Pulumi.ResourceOptions))
			: base("azure:network/localNetworkGateway:LocalNetworkGateway", name, SerialiseArgs(args), opts) {
			AddressSpaces = base.Outputs["addressSpaces"].Select(item => Protobuf.ToList(item, item1 => Protobuf.ToString(item1)));
			BgpSettings = base.Outputs["bgpSettings"].Select(item => LocalNetworkGatewayBgpSetting.FromProtobuf(item));
			GatewayAddress = base.Outputs["gatewayAddress"].Select(item => Protobuf.ToString(item));
			Location = base.Outputs["location"].Select(item => Protobuf.ToString(item));
			Name = base.Outputs["name"].Select(item => Protobuf.ToString(item));
			ResourceGroupName = base.Outputs["resourceGroupName"].Select(item => Protobuf.ToString(item));
			Tags = base.Outputs["tags"].Select(item => Protobuf.ToMap(item));
		} // ctor

		private static Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>> SerialiseArgs(LocalNetworkGatewayArgs args) {
			var props = new Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>();
			props["addressSpaces"] = Protobuf.ToProtobuf(args.AddressSpaces, item => Protobuf.ToProtobuf(item));
			props["bgpSettings"] = Protobuf.ToProtobuf(args.BgpSettings);
			props["gatewayAddress"] = Protobuf.ToProtobuf(args.GatewayAddress);
			props["location"] = Protobuf.ToProtobuf(args.Location);
			props["name"] = Protobuf.ToProtobuf(args.Name);
			props["resourceGroupName"] = Protobuf.ToProtobuf(args.ResourceGroupName);
			props["tags"] = Protobuf.ToProtobuf(args.Tags);
			return props;
		} // SerialiseArgs

	} // LocalNetworkGateway
} // Pulumi.Azure.Network
