// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class ProtectionPolicyVM extends pulumi.CustomResource {
    /**
     * Get an existing ProtectionPolicyVM resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProtectionPolicyVMState, opts?: pulumi.CustomResourceOptions): ProtectionPolicyVM {
        return new ProtectionPolicyVM(name, <any>state, { ...opts, id: id });
    }

    public readonly backup: pulumi.Output<{ frequency: string, time: string, weekdays?: string[] }>;
    public readonly name: pulumi.Output<string>;
    public readonly recoveryVaultName: pulumi.Output<string>;
    public readonly resourceGroupName: pulumi.Output<string>;
    public readonly retentionDaily: pulumi.Output<{ count: number } | undefined>;
    public readonly retentionMonthly: pulumi.Output<{ count: number, weekdays: string[], weeks: string[] } | undefined>;
    public readonly retentionWeekly: pulumi.Output<{ count: number, weekdays: string[] } | undefined>;
    public readonly retentionYearly: pulumi.Output<{ count: number, months: string[], weekdays: string[], weeks: string[] } | undefined>;
    public readonly tags: pulumi.Output<{[key: string]: any}>;
    public readonly timezone: pulumi.Output<string | undefined>;

    /**
     * Create a ProtectionPolicyVM resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProtectionPolicyVMArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProtectionPolicyVMArgs | ProtectionPolicyVMState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: ProtectionPolicyVMState = argsOrState as ProtectionPolicyVMState | undefined;
            inputs["backup"] = state ? state.backup : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["recoveryVaultName"] = state ? state.recoveryVaultName : undefined;
            inputs["resourceGroupName"] = state ? state.resourceGroupName : undefined;
            inputs["retentionDaily"] = state ? state.retentionDaily : undefined;
            inputs["retentionMonthly"] = state ? state.retentionMonthly : undefined;
            inputs["retentionWeekly"] = state ? state.retentionWeekly : undefined;
            inputs["retentionYearly"] = state ? state.retentionYearly : undefined;
            inputs["tags"] = state ? state.tags : undefined;
            inputs["timezone"] = state ? state.timezone : undefined;
        } else {
            const args = argsOrState as ProtectionPolicyVMArgs | undefined;
            if (!args || args.backup === undefined) {
                throw new Error("Missing required property 'backup'");
            }
            if (!args || args.recoveryVaultName === undefined) {
                throw new Error("Missing required property 'recoveryVaultName'");
            }
            if (!args || args.resourceGroupName === undefined) {
                throw new Error("Missing required property 'resourceGroupName'");
            }
            inputs["backup"] = args ? args.backup : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["recoveryVaultName"] = args ? args.recoveryVaultName : undefined;
            inputs["resourceGroupName"] = args ? args.resourceGroupName : undefined;
            inputs["retentionDaily"] = args ? args.retentionDaily : undefined;
            inputs["retentionMonthly"] = args ? args.retentionMonthly : undefined;
            inputs["retentionWeekly"] = args ? args.retentionWeekly : undefined;
            inputs["retentionYearly"] = args ? args.retentionYearly : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["timezone"] = args ? args.timezone : undefined;
        }
        super("azure:recoveryservices/protectionPolicyVM:ProtectionPolicyVM", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ProtectionPolicyVM resources.
 */
export interface ProtectionPolicyVMState {
    readonly backup?: pulumi.Input<{ frequency: pulumi.Input<string>, time: pulumi.Input<string>, weekdays?: pulumi.Input<pulumi.Input<string>[]> }>;
    readonly name?: pulumi.Input<string>;
    readonly recoveryVaultName?: pulumi.Input<string>;
    readonly resourceGroupName?: pulumi.Input<string>;
    readonly retentionDaily?: pulumi.Input<{ count: pulumi.Input<number> }>;
    readonly retentionMonthly?: pulumi.Input<{ count: pulumi.Input<number>, weekdays: pulumi.Input<pulumi.Input<string>[]>, weeks: pulumi.Input<pulumi.Input<string>[]> }>;
    readonly retentionWeekly?: pulumi.Input<{ count: pulumi.Input<number>, weekdays: pulumi.Input<pulumi.Input<string>[]> }>;
    readonly retentionYearly?: pulumi.Input<{ count: pulumi.Input<number>, months: pulumi.Input<pulumi.Input<string>[]>, weekdays: pulumi.Input<pulumi.Input<string>[]>, weeks: pulumi.Input<pulumi.Input<string>[]> }>;
    readonly tags?: pulumi.Input<{[key: string]: any}>;
    readonly timezone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ProtectionPolicyVM resource.
 */
export interface ProtectionPolicyVMArgs {
    readonly backup: pulumi.Input<{ frequency: pulumi.Input<string>, time: pulumi.Input<string>, weekdays?: pulumi.Input<pulumi.Input<string>[]> }>;
    readonly name?: pulumi.Input<string>;
    readonly recoveryVaultName: pulumi.Input<string>;
    readonly resourceGroupName: pulumi.Input<string>;
    readonly retentionDaily?: pulumi.Input<{ count: pulumi.Input<number> }>;
    readonly retentionMonthly?: pulumi.Input<{ count: pulumi.Input<number>, weekdays: pulumi.Input<pulumi.Input<string>[]>, weeks: pulumi.Input<pulumi.Input<string>[]> }>;
    readonly retentionWeekly?: pulumi.Input<{ count: pulumi.Input<number>, weekdays: pulumi.Input<pulumi.Input<string>[]> }>;
    readonly retentionYearly?: pulumi.Input<{ count: pulumi.Input<number>, months: pulumi.Input<pulumi.Input<string>[]>, weekdays: pulumi.Input<pulumi.Input<string>[]>, weeks: pulumi.Input<pulumi.Input<string>[]> }>;
    readonly tags?: pulumi.Input<{[key: string]: any}>;
    readonly timezone?: pulumi.Input<string>;
}
