// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getSharedImage(args: GetSharedImageArgs, opts?: pulumi.InvokeOptions): Promise<GetSharedImageResult> {
    return pulumi.runtime.invoke("azure:compute/getSharedImage:getSharedImage", {
        "galleryName": args.galleryName,
        "name": args.name,
        "resourceGroupName": args.resourceGroupName,
    }, opts);
}

/**
 * A collection of arguments for invoking getSharedImage.
 */
export interface GetSharedImageArgs {
    readonly galleryName: string;
    readonly name: string;
    readonly resourceGroupName: string;
}

/**
 * A collection of values returned by getSharedImage.
 */
export interface GetSharedImageResult {
    readonly description: string;
    readonly eula: string;
    readonly identifiers: { offer: string, publisher: string, sku: string }[];
    readonly location: string;
    readonly osType: string;
    readonly privacyStatementUri: string;
    readonly releaseNoteUri: string;
    readonly tags: {[key: string]: any};
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
