// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Linq;

namespace Pulumi.Azure.Operationalinsights {

	/// <summary>
	/// The set of arguments for constructing a AnalyticsWorkspace resource.
	/// </summary>
	public struct AnalyticsWorkspaceArgs {
		/// <summary>
		/// Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Location { get; set; }

		/// <summary>
		/// Specifies the name of the Log Analytics Workspace. Workspace name should include 4-63 letters, digits or '-'. The '-' shouldn't be the first or the last symbol. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// The name of the resource group in which the Log Analytics workspace is created. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// The workspace data retention in days. Possible values range between 30 and 730.
		/// </summary>
		public Pulumi.IO<int> RetentionInDays { get; set; }

		/// <summary>
		/// Specifies the Sku of the Log Analytics Workspace. Possible values are `Free`, `PerNode`, `Premium`, `Standard`, `Standalone`, `Unlimited`, and `PerGB2018` (new Sku as of `2018-04-03`).
		/// </summary>
		public Pulumi.IO<string> Sku { get; set; }

		/// <summary>
		/// A mapping of tags to assign to the resource.
		/// </summary>
		public Pulumi.IO<System.Collections.Generic.Dictionary<string, string>> Tags { get; set; }

	} // AnalyticsWorkspaceArgs

	/// <summary>
	/// Manages a Log Analytics (formally Operational Insights) Workspace.
	/// </summary>
	public class AnalyticsWorkspace : Pulumi.CustomResource {
		/// <summary>
		/// Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Location { get; set; }

		/// <summary>
		/// Specifies the name of the Log Analytics Workspace. Workspace name should include 4-63 letters, digits or '-'. The '-' shouldn't be the first or the last symbol. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// The Portal URL for the Log Analytics Workspace.
		/// </summary>
		public Pulumi.IO<string> PortalUrl { get; set; }

		/// <summary>
		/// The Primary shared key for the Log Analytics Workspace.
		/// </summary>
		public Pulumi.IO<string> PrimarySharedKey { get; set; }

		/// <summary>
		/// The name of the resource group in which the Log Analytics workspace is created. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// The workspace data retention in days. Possible values range between 30 and 730.
		/// </summary>
		public Pulumi.IO<int> RetentionInDays { get; set; }

		/// <summary>
		/// The Secondary shared key for the Log Analytics Workspace.
		/// </summary>
		public Pulumi.IO<string> SecondarySharedKey { get; set; }

		/// <summary>
		/// Specifies the Sku of the Log Analytics Workspace. Possible values are `Free`, `PerNode`, `Premium`, `Standard`, `Standalone`, `Unlimited`, and `PerGB2018` (new Sku as of `2018-04-03`).
		/// </summary>
		public Pulumi.IO<string> Sku { get; set; }

		/// <summary>
		/// A mapping of tags to assign to the resource.
		/// </summary>
		public Pulumi.IO<System.Collections.Generic.Dictionary<string, string>> Tags { get; set; }

		/// <summary>
		/// The Workspace (or Customer) ID for the Log Analytics Workspace.
		/// </summary>
		public Pulumi.IO<string> WorkspaceId { get; set; }

		public AnalyticsWorkspace(string name, AnalyticsWorkspaceArgs args, Pulumi.ResourceOptions opts = default(Pulumi.ResourceOptions))
			: base("azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace", name, SerialiseArgs(args), opts) {
			Location = base.Outputs["location"].Select(item => Protobuf.ToString(item));
			Name = base.Outputs["name"].Select(item => Protobuf.ToString(item));
			PortalUrl = base.Outputs["portalUrl"].Select(item => Protobuf.ToString(item));
			PrimarySharedKey = base.Outputs["primarySharedKey"].Select(item => Protobuf.ToString(item));
			ResourceGroupName = base.Outputs["resourceGroupName"].Select(item => Protobuf.ToString(item));
			RetentionInDays = base.Outputs["retentionInDays"].Select(item => Protobuf.ToInt(item));
			SecondarySharedKey = base.Outputs["secondarySharedKey"].Select(item => Protobuf.ToString(item));
			Sku = base.Outputs["sku"].Select(item => Protobuf.ToString(item));
			Tags = base.Outputs["tags"].Select(item => Protobuf.ToMap(item));
			WorkspaceId = base.Outputs["workspaceId"].Select(item => Protobuf.ToString(item));
		} // ctor

		private static Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>> SerialiseArgs(AnalyticsWorkspaceArgs args) {
			var props = new Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>();
			props["location"] = Protobuf.ToProtobuf(args.Location);
			props["name"] = Protobuf.ToProtobuf(args.Name);
			props["resourceGroupName"] = Protobuf.ToProtobuf(args.ResourceGroupName);
			props["retentionInDays"] = Protobuf.ToProtobuf(args.RetentionInDays);
			props["sku"] = Protobuf.ToProtobuf(args.Sku);
			props["tags"] = Protobuf.ToProtobuf(args.Tags);
			props["portalUrl"] = null; //out
			props["primarySharedKey"] = null; //out
			props["secondarySharedKey"] = null; //out
			props["workspaceId"] = null; //out
			return props;
		} // SerialiseArgs

	} // AnalyticsWorkspace
} // Pulumi.Azure.Operationalinsights
