// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Linq;

namespace Pulumi.Azure.Storage {

	/// <summary>
	/// The set of arguments for constructing a Share resource.
	/// </summary>
	public struct ShareArgs {
		/// <summary>
		/// The name of the share. Must be unique within the storage account where the share is located.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// The maximum size of the share, in gigabytes. Must be greater than 0, and less than or equal to 5 TB (5120 GB). Default is 5120.
		/// </summary>
		public Pulumi.IO<int> Quota { get; set; }

		/// <summary>
		/// The name of the resource group in which to
		/// create the share. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// Specifies the storage account in which to create the share.
		/// Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> StorageAccountName { get; set; }

	} // ShareArgs

	/// <summary>
	/// Manage an Azure Storage File Share.
	/// </summary>
	public class Share : Pulumi.CustomResource {
		/// <summary>
		/// The name of the share. Must be unique within the storage account where the share is located.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// The maximum size of the share, in gigabytes. Must be greater than 0, and less than or equal to 5 TB (5120 GB). Default is 5120.
		/// </summary>
		public Pulumi.IO<int> Quota { get; set; }

		/// <summary>
		/// The name of the resource group in which to
		/// create the share. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// Specifies the storage account in which to create the share.
		/// Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> StorageAccountName { get; set; }

		/// <summary>
		/// The URL of the share
		/// </summary>
		public Pulumi.IO<string> Url { get; set; }

		public Share(string name, ShareArgs args, Pulumi.ResourceOptions opts = default(Pulumi.ResourceOptions))
			: base("azure:storage/share:Share", name, SerialiseArgs(args), opts) {
			Name = base.Outputs["name"].Select(item => Protobuf.ToString(item));
			Quota = base.Outputs["quota"].Select(item => Protobuf.ToInt(item));
			ResourceGroupName = base.Outputs["resourceGroupName"].Select(item => Protobuf.ToString(item));
			StorageAccountName = base.Outputs["storageAccountName"].Select(item => Protobuf.ToString(item));
			Url = base.Outputs["url"].Select(item => Protobuf.ToString(item));
		} // ctor

		private static Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>> SerialiseArgs(ShareArgs args) {
			var props = new Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>();
			props["name"] = Protobuf.ToProtobuf(args.Name);
			props["quota"] = Protobuf.ToProtobuf(args.Quota);
			props["resourceGroupName"] = Protobuf.ToProtobuf(args.ResourceGroupName);
			props["storageAccountName"] = Protobuf.ToProtobuf(args.StorageAccountName);
			props["url"] = null; //out
			return props;
		} // SerialiseArgs

	} // Share
} // Pulumi.Azure.Storage
