// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Linq;

namespace Pulumi.Azure.Scheduler {

	public sealed class GetJobCollectionQuota : Pulumi.IProtobuf {
		public int MaxJobCount { get; set; }
		public string MaxRecurrenceFrequency { get; set; }
		public int MaxRecurrenceInterval { get; set; }
		public int MaxRetryInterval { get; set; }

		public Google.Protobuf.WellKnownTypes.Value ToProtobuf() {
			return Protobuf.ToProtobuf(
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("max_job_count", Protobuf.ToProtobuf(MaxJobCount)),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("max_recurrence_frequency", Protobuf.ToProtobuf(MaxRecurrenceFrequency)),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("max_recurrence_interval", Protobuf.ToProtobuf(MaxRecurrenceInterval)),
				new KeyValuePair<string, Google.Protobuf.WellKnownTypes.Value>("max_retry_interval", Protobuf.ToProtobuf(MaxRetryInterval)));
		} // ToProtobuf

		public static GetJobCollectionQuota FromProtobuf(Google.Protobuf.WellKnownTypes.Value value) {
			var obj = value.StructValue;
			var result = new GetJobCollectionQuota();
				if (obj.Fields.ContainsKey("max_job_count")) {
					result.MaxJobCount = Protobuf.ToInt(obj.Fields["max_job_count"]);
				}
				if (obj.Fields.ContainsKey("max_recurrence_frequency")) {
					result.MaxRecurrenceFrequency = Protobuf.ToString(obj.Fields["max_recurrence_frequency"]);
				}
				if (obj.Fields.ContainsKey("max_recurrence_interval")) {
					result.MaxRecurrenceInterval = Protobuf.ToInt(obj.Fields["max_recurrence_interval"]);
				}
				if (obj.Fields.ContainsKey("max_retry_interval")) {
					result.MaxRetryInterval = Protobuf.ToInt(obj.Fields["max_retry_interval"]);
				}
			return result;
		} // FromProtobuf

	} // GetJobCollectionQuota

	/// <summary>
	/// A collection of arguments for invoking getJobCollection.
	/// </summary>
	public struct GetJobCollectionArgs {
		/// <summary>
		/// Specifies the name of the Scheduler Job Collection.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// Specifies the name of the resource group in which the Scheduler Job Collection resides.
		/// </summary>
		public string ResourceGroupName { get; set; }

	} // GetJobCollectionArgs

	/// <summary>
	/// A collection of values returned by getJobCollection.
	/// </summary>
	public struct GetJobCollectionResult {
		/// <summary>
		/// The Azure location where the resource exists.
		/// </summary>
		public string Location { get; set; }

		/// <summary>
		/// The Job collection quotas as documented in the `quota` block below.
		/// </summary>
		public GetJobCollectionQuota[] Quotas { get; set; }

		/// <summary>
		/// The Job Collection's pricing level's SKU.
		/// </summary>
		public string Sku { get; set; }

		/// <summary>
		/// The Job Collection's state.
		/// </summary>
		public string State { get; set; }

		/// <summary>
		/// A mapping of tags assigned to the resource.
		/// </summary>
		public System.Collections.Generic.Dictionary<string, string> Tags { get; set; }

		/// <summary>
		/// id is the provider-assigned unique ID for this managed resource.
		/// </summary>
		public string Id { get; set; }

	} // GetJobCollectionResult

	public static partial class SchedulerModule {
		/// <summary>
		/// Use this data source to access information about an existing Scheduler Job Collection.
		/// 
		/// > **NOTE:** Support for Scheduler Job Collections has been deprecated by Microsoft in favour of Logic Apps ([more information can be found at this link](https://docs.microsoft.com/en-us/azure/scheduler/migrate-from-scheduler-to-logic-apps)) - as such we plan to remove support for this data source as a part of version 2.0 of the AzureRM Provider.
		/// </summary>
		public static System.Threading.Tasks.Task<GetJobCollectionResult> GetJobCollection(GetJobCollectionArgs args, Pulumi.InvokeOptions opts = default(Pulumi.InvokeOptions)) {
			var invokeArgs = new Google.Protobuf.WellKnownTypes.Struct();
			invokeArgs.Fields["name"] = Protobuf.ToProtobuf(args.Name);
			invokeArgs.Fields["resourceGroupName"] = Protobuf.ToProtobuf(args.ResourceGroupName);

			var task = Pulumi.Runtime.InvokeAsync("azure:scheduler/getJobCollection:getJobCollection", invokeArgs, opts);

			return task.ContinueWith(response => {
				var protobuf = response.Result;
				var result = new GetJobCollectionResult();
				if (protobuf.Fields.ContainsKey("location")) {
					result.Location = Protobuf.ToString(protobuf.Fields["location"]);
				}
				if (protobuf.Fields.ContainsKey("quotas")) {
					result.Quotas = Protobuf.ToList(protobuf.Fields["quotas"], item => GetJobCollectionQuota.FromProtobuf(item));
				}
				if (protobuf.Fields.ContainsKey("sku")) {
					result.Sku = Protobuf.ToString(protobuf.Fields["sku"]);
				}
				if (protobuf.Fields.ContainsKey("state")) {
					result.State = Protobuf.ToString(protobuf.Fields["state"]);
				}
				if (protobuf.Fields.ContainsKey("tags")) {
					result.Tags = Protobuf.ToMap(protobuf.Fields["tags"]);
				}
				if (protobuf.Fields.ContainsKey("id")) {
					result.Id = Protobuf.ToString(protobuf.Fields["id"]);
				}
				return result;
			});
		} // GetJobCollection

	} // SchedulerModule
} // Pulumi.Azure.Scheduler
