// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Linq;

namespace Pulumi.Azure.Logicapps {

	/// <summary>
	/// The set of arguments for constructing a ActionCustom resource.
	/// </summary>
	public struct ActionCustomArgs {
		/// <summary>
		/// Specifies the JSON Blob defining the Body of this Custom Action.
		/// </summary>
		public Pulumi.IO<string> Body { get; set; }

		/// <summary>
		/// Specifies the ID of the Logic App Workflow. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> LogicAppId { get; set; }

		/// <summary>
		/// Specifies the name of the HTTP Action to be created within the Logic App Workflow. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

	} // ActionCustomArgs

	/// <summary>
	/// Manages a Custom Action within a Logic App Workflow
	/// </summary>
	public class ActionCustom : Pulumi.CustomResource {
		/// <summary>
		/// Specifies the JSON Blob defining the Body of this Custom Action.
		/// </summary>
		public Pulumi.IO<string> Body { get; set; }

		/// <summary>
		/// Specifies the ID of the Logic App Workflow. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> LogicAppId { get; set; }

		/// <summary>
		/// Specifies the name of the HTTP Action to be created within the Logic App Workflow. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		public ActionCustom(string name, ActionCustomArgs args, Pulumi.ResourceOptions opts = default(Pulumi.ResourceOptions))
			: base("azure:logicapps/actionCustom:ActionCustom", name, SerialiseArgs(args), opts) {
			Body = base.Outputs["body"].Select(item => Protobuf.ToString(item));
			LogicAppId = base.Outputs["logicAppId"].Select(item => Protobuf.ToString(item));
			Name = base.Outputs["name"].Select(item => Protobuf.ToString(item));
		} // ctor

		private static Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>> SerialiseArgs(ActionCustomArgs args) {
			var props = new Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>();
			props["body"] = Protobuf.ToProtobuf(args.Body);
			props["logicAppId"] = Protobuf.ToProtobuf(args.LogicAppId);
			props["name"] = Protobuf.ToProtobuf(args.Name);
			return props;
		} // SerialiseArgs

	} // ActionCustom
} // Pulumi.Azure.Logicapps
