// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Linq;

namespace Pulumi.Azure.Appservice {

	/// <summary>
	/// The set of arguments for constructing a CustomHostnameBinding resource.
	/// </summary>
	public struct CustomHostnameBindingArgs {
		/// <summary>
		/// The name of the App Service in which to add the Custom Hostname Binding. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> AppServiceName { get; set; }

		/// <summary>
		/// Specifies the Custom Hostname to use for the App Service, example `www.example.com`. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Hostname { get; set; }

		/// <summary>
		/// The name of the resource group in which the App Service exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

	} // CustomHostnameBindingArgs

	/// <summary>
	/// Manages a Hostname Binding within an App Service.
	/// </summary>
	public class CustomHostnameBinding : Pulumi.CustomResource {
		/// <summary>
		/// The name of the App Service in which to add the Custom Hostname Binding. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> AppServiceName { get; set; }

		/// <summary>
		/// Specifies the Custom Hostname to use for the App Service, example `www.example.com`. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Hostname { get; set; }

		/// <summary>
		/// The name of the resource group in which the App Service exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		public CustomHostnameBinding(string name, CustomHostnameBindingArgs args, Pulumi.ResourceOptions opts = default(Pulumi.ResourceOptions))
			: base("azure:appservice/customHostnameBinding:CustomHostnameBinding", name, SerialiseArgs(args), opts) {
			AppServiceName = base.Outputs["appServiceName"].Select(item => Protobuf.ToString(item));
			Hostname = base.Outputs["hostname"].Select(item => Protobuf.ToString(item));
			ResourceGroupName = base.Outputs["resourceGroupName"].Select(item => Protobuf.ToString(item));
		} // ctor

		private static Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>> SerialiseArgs(CustomHostnameBindingArgs args) {
			var props = new Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>();
			props["appServiceName"] = Protobuf.ToProtobuf(args.AppServiceName);
			props["hostname"] = Protobuf.ToProtobuf(args.Hostname);
			props["resourceGroupName"] = Protobuf.ToProtobuf(args.ResourceGroupName);
			return props;
		} // SerialiseArgs

	} // CustomHostnameBinding
} // Pulumi.Azure.Appservice
