// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getLab(args: GetLabArgs, opts?: pulumi.InvokeOptions): Promise<GetLabResult> {
    return pulumi.runtime.invoke("azure:devtest/getLab:getLab", {
        "name": args.name,
        "resourceGroupName": args.resourceGroupName,
    }, opts);
}

/**
 * A collection of arguments for invoking getLab.
 */
export interface GetLabArgs {
    readonly name: string;
    readonly resourceGroupName: string;
}

/**
 * A collection of values returned by getLab.
 */
export interface GetLabResult {
    readonly artifactsStorageAccountId: string;
    readonly defaultPremiumStorageAccountId: string;
    readonly defaultStorageAccountId: string;
    readonly keyVaultId: string;
    readonly location: string;
    readonly premiumDataDiskStorageAccountId: string;
    readonly storageType: string;
    readonly tags: {[key: string]: any};
    readonly uniqueIdentifier: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
