// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class RunBook extends pulumi.CustomResource {
    /**
     * Get an existing RunBook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RunBookState, opts?: pulumi.CustomResourceOptions): RunBook {
        return new RunBook(name, <any>state, { ...opts, id: id });
    }

    public readonly accountName: pulumi.Output<string>;
    public readonly content: pulumi.Output<string>;
    public readonly description: pulumi.Output<string | undefined>;
    public readonly location: pulumi.Output<string>;
    public readonly logProgress: pulumi.Output<boolean>;
    public readonly logVerbose: pulumi.Output<boolean>;
    public readonly name: pulumi.Output<string>;
    public readonly publishContentLink: pulumi.Output<{ hash?: { algorithm: string, value: string }, uri: string, version?: string }>;
    public readonly resourceGroupName: pulumi.Output<string>;
    public readonly runbookType: pulumi.Output<string>;
    public readonly tags: pulumi.Output<{[key: string]: any}>;

    /**
     * Create a RunBook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RunBookArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RunBookArgs | RunBookState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: RunBookState = argsOrState as RunBookState | undefined;
            inputs["accountName"] = state ? state.accountName : undefined;
            inputs["content"] = state ? state.content : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["location"] = state ? state.location : undefined;
            inputs["logProgress"] = state ? state.logProgress : undefined;
            inputs["logVerbose"] = state ? state.logVerbose : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["publishContentLink"] = state ? state.publishContentLink : undefined;
            inputs["resourceGroupName"] = state ? state.resourceGroupName : undefined;
            inputs["runbookType"] = state ? state.runbookType : undefined;
            inputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as RunBookArgs | undefined;
            if (!args || args.accountName === undefined) {
                throw new Error("Missing required property 'accountName'");
            }
            if (!args || args.location === undefined) {
                throw new Error("Missing required property 'location'");
            }
            if (!args || args.logProgress === undefined) {
                throw new Error("Missing required property 'logProgress'");
            }
            if (!args || args.logVerbose === undefined) {
                throw new Error("Missing required property 'logVerbose'");
            }
            if (!args || args.publishContentLink === undefined) {
                throw new Error("Missing required property 'publishContentLink'");
            }
            if (!args || args.resourceGroupName === undefined) {
                throw new Error("Missing required property 'resourceGroupName'");
            }
            if (!args || args.runbookType === undefined) {
                throw new Error("Missing required property 'runbookType'");
            }
            inputs["accountName"] = args ? args.accountName : undefined;
            inputs["content"] = args ? args.content : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["location"] = args ? args.location : undefined;
            inputs["logProgress"] = args ? args.logProgress : undefined;
            inputs["logVerbose"] = args ? args.logVerbose : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["publishContentLink"] = args ? args.publishContentLink : undefined;
            inputs["resourceGroupName"] = args ? args.resourceGroupName : undefined;
            inputs["runbookType"] = args ? args.runbookType : undefined;
            inputs["tags"] = args ? args.tags : undefined;
        }
        super("azure:automation/runBook:RunBook", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RunBook resources.
 */
export interface RunBookState {
    readonly accountName?: pulumi.Input<string>;
    readonly content?: pulumi.Input<string>;
    readonly description?: pulumi.Input<string>;
    readonly location?: pulumi.Input<string>;
    readonly logProgress?: pulumi.Input<boolean>;
    readonly logVerbose?: pulumi.Input<boolean>;
    readonly name?: pulumi.Input<string>;
    readonly publishContentLink?: pulumi.Input<{ hash?: pulumi.Input<{ algorithm: pulumi.Input<string>, value: pulumi.Input<string> }>, uri: pulumi.Input<string>, version?: pulumi.Input<string> }>;
    readonly resourceGroupName?: pulumi.Input<string>;
    readonly runbookType?: pulumi.Input<string>;
    readonly tags?: pulumi.Input<{[key: string]: any}>;
}

/**
 * The set of arguments for constructing a RunBook resource.
 */
export interface RunBookArgs {
    readonly accountName: pulumi.Input<string>;
    readonly content?: pulumi.Input<string>;
    readonly description?: pulumi.Input<string>;
    readonly location: pulumi.Input<string>;
    readonly logProgress: pulumi.Input<boolean>;
    readonly logVerbose: pulumi.Input<boolean>;
    readonly name?: pulumi.Input<string>;
    readonly publishContentLink: pulumi.Input<{ hash?: pulumi.Input<{ algorithm: pulumi.Input<string>, value: pulumi.Input<string> }>, uri: pulumi.Input<string>, version?: pulumi.Input<string> }>;
    readonly resourceGroupName: pulumi.Input<string>;
    readonly runbookType: pulumi.Input<string>;
    readonly tags?: pulumi.Input<{[key: string]: any}>;
}
