// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Linq;

namespace Pulumi.Azure.Automation {

	/// <summary>
	/// The set of arguments for constructing a DscNodeConfiguration resource.
	/// </summary>
	public struct DscNodeConfigurationArgs {
		/// <summary>
		/// The name of the automation account in which the DSC Node Configuration is created. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> AutomationAccountName { get; set; }

		/// <summary>
		/// The PowerShell DSC Node Configuration (mof content).
		/// </summary>
		public Pulumi.IO<string> ContentEmbedded { get; set; }

		/// <summary>
		/// Specifies the name of the DSC Node Configuration. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// The name of the resource group in which the DSC Node Configuration is created. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

	} // DscNodeConfigurationArgs

	/// <summary>
	/// Manages a Automation DSC Node Configuration.
	/// </summary>
	public class DscNodeConfiguration : Pulumi.CustomResource {
		/// <summary>
		/// The name of the automation account in which the DSC Node Configuration is created. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> AutomationAccountName { get; set; }

		public Pulumi.IO<string> ConfigurationName { get; set; }

		/// <summary>
		/// The PowerShell DSC Node Configuration (mof content).
		/// </summary>
		public Pulumi.IO<string> ContentEmbedded { get; set; }

		/// <summary>
		/// Specifies the name of the DSC Node Configuration. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// The name of the resource group in which the DSC Node Configuration is created. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		public DscNodeConfiguration(string name, DscNodeConfigurationArgs args, Pulumi.ResourceOptions opts = default(Pulumi.ResourceOptions))
			: base("azure:automation/dscNodeConfiguration:DscNodeConfiguration", name, SerialiseArgs(args), opts) {
			AutomationAccountName = base.Outputs["automationAccountName"].Select(item => Protobuf.ToString(item));
			ConfigurationName = base.Outputs["configurationName"].Select(item => Protobuf.ToString(item));
			ContentEmbedded = base.Outputs["contentEmbedded"].Select(item => Protobuf.ToString(item));
			Name = base.Outputs["name"].Select(item => Protobuf.ToString(item));
			ResourceGroupName = base.Outputs["resourceGroupName"].Select(item => Protobuf.ToString(item));
		} // ctor

		private static Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>> SerialiseArgs(DscNodeConfigurationArgs args) {
			var props = new Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>();
			props["automationAccountName"] = Protobuf.ToProtobuf(args.AutomationAccountName);
			props["contentEmbedded"] = Protobuf.ToProtobuf(args.ContentEmbedded);
			props["name"] = Protobuf.ToProtobuf(args.Name);
			props["resourceGroupName"] = Protobuf.ToProtobuf(args.ResourceGroupName);
			props["configurationName"] = null; //out
			return props;
		} // SerialiseArgs

	} // DscNodeConfiguration
} // Pulumi.Azure.Automation
