// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class EventHubNamespaceAuthorizationRule extends pulumi.CustomResource {
    /**
     * Get an existing EventHubNamespaceAuthorizationRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EventHubNamespaceAuthorizationRuleState, opts?: pulumi.CustomResourceOptions): EventHubNamespaceAuthorizationRule {
        return new EventHubNamespaceAuthorizationRule(name, <any>state, { ...opts, id: id });
    }

    public readonly listen: pulumi.Output<boolean | undefined>;
    public readonly location: pulumi.Output<string | undefined>;
    public readonly manage: pulumi.Output<boolean | undefined>;
    public readonly name: pulumi.Output<string>;
    public readonly namespaceName: pulumi.Output<string>;
    public /*out*/ readonly primaryConnectionString: pulumi.Output<string>;
    public /*out*/ readonly primaryKey: pulumi.Output<string>;
    public readonly resourceGroupName: pulumi.Output<string>;
    public /*out*/ readonly secondaryConnectionString: pulumi.Output<string>;
    public /*out*/ readonly secondaryKey: pulumi.Output<string>;
    public readonly send: pulumi.Output<boolean | undefined>;

    /**
     * Create a EventHubNamespaceAuthorizationRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EventHubNamespaceAuthorizationRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EventHubNamespaceAuthorizationRuleArgs | EventHubNamespaceAuthorizationRuleState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: EventHubNamespaceAuthorizationRuleState = argsOrState as EventHubNamespaceAuthorizationRuleState | undefined;
            inputs["listen"] = state ? state.listen : undefined;
            inputs["location"] = state ? state.location : undefined;
            inputs["manage"] = state ? state.manage : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["namespaceName"] = state ? state.namespaceName : undefined;
            inputs["primaryConnectionString"] = state ? state.primaryConnectionString : undefined;
            inputs["primaryKey"] = state ? state.primaryKey : undefined;
            inputs["resourceGroupName"] = state ? state.resourceGroupName : undefined;
            inputs["secondaryConnectionString"] = state ? state.secondaryConnectionString : undefined;
            inputs["secondaryKey"] = state ? state.secondaryKey : undefined;
            inputs["send"] = state ? state.send : undefined;
        } else {
            const args = argsOrState as EventHubNamespaceAuthorizationRuleArgs | undefined;
            if (!args || args.namespaceName === undefined) {
                throw new Error("Missing required property 'namespaceName'");
            }
            if (!args || args.resourceGroupName === undefined) {
                throw new Error("Missing required property 'resourceGroupName'");
            }
            inputs["listen"] = args ? args.listen : undefined;
            inputs["location"] = args ? args.location : undefined;
            inputs["manage"] = args ? args.manage : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["namespaceName"] = args ? args.namespaceName : undefined;
            inputs["resourceGroupName"] = args ? args.resourceGroupName : undefined;
            inputs["send"] = args ? args.send : undefined;
            inputs["primaryConnectionString"] = undefined /*out*/;
            inputs["primaryKey"] = undefined /*out*/;
            inputs["secondaryConnectionString"] = undefined /*out*/;
            inputs["secondaryKey"] = undefined /*out*/;
        }
        super("azure:eventhub/eventHubNamespaceAuthorizationRule:EventHubNamespaceAuthorizationRule", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EventHubNamespaceAuthorizationRule resources.
 */
export interface EventHubNamespaceAuthorizationRuleState {
    readonly listen?: pulumi.Input<boolean>;
    readonly location?: pulumi.Input<string>;
    readonly manage?: pulumi.Input<boolean>;
    readonly name?: pulumi.Input<string>;
    readonly namespaceName?: pulumi.Input<string>;
    readonly primaryConnectionString?: pulumi.Input<string>;
    readonly primaryKey?: pulumi.Input<string>;
    readonly resourceGroupName?: pulumi.Input<string>;
    readonly secondaryConnectionString?: pulumi.Input<string>;
    readonly secondaryKey?: pulumi.Input<string>;
    readonly send?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a EventHubNamespaceAuthorizationRule resource.
 */
export interface EventHubNamespaceAuthorizationRuleArgs {
    readonly listen?: pulumi.Input<boolean>;
    readonly location?: pulumi.Input<string>;
    readonly manage?: pulumi.Input<boolean>;
    readonly name?: pulumi.Input<string>;
    readonly namespaceName: pulumi.Input<string>;
    readonly resourceGroupName: pulumi.Input<string>;
    readonly send?: pulumi.Input<boolean>;
}
