// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Linq;

namespace Pulumi.Azure.Eventhub {

	/// <summary>
	/// The set of arguments for constructing a NamespaceAuthorizationRule resource.
	/// </summary>
	public struct NamespaceAuthorizationRuleArgs {
		/// <summary>
		/// Grants listen access to this this Authorization Rule. Defaults to `false`.
		/// </summary>
		public Pulumi.IO<bool> Listen { get; set; }

		/// <summary>
		/// Grants manage access to this this Authorization Rule. When this property is `true` - both `listen` and `send` must be too. Defaults to `false`.
		/// </summary>
		public Pulumi.IO<bool> Manage { get; set; }

		/// <summary>
		/// Specifies the name of the ServiceBus Namespace Authorization Rule resource. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// Specifies the name of the ServiceBus Namespace. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> NamespaceName { get; set; }

		/// <summary>
		/// The name of the resource group in which the ServiceBus Namespace exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// Grants send access to this this Authorization Rule. Defaults to `false`.
		/// </summary>
		public Pulumi.IO<bool> Send { get; set; }

	} // NamespaceAuthorizationRuleArgs

	/// <summary>
	/// Manages a ServiceBus Namespace authorization Rule within a ServiceBus.
	/// </summary>
	public class NamespaceAuthorizationRule : Pulumi.CustomResource {
		/// <summary>
		/// Grants listen access to this this Authorization Rule. Defaults to `false`.
		/// </summary>
		public Pulumi.IO<bool> Listen { get; set; }

		/// <summary>
		/// Grants manage access to this this Authorization Rule. When this property is `true` - both `listen` and `send` must be too. Defaults to `false`.
		/// </summary>
		public Pulumi.IO<bool> Manage { get; set; }

		/// <summary>
		/// Specifies the name of the ServiceBus Namespace Authorization Rule resource. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> Name { get; set; }

		/// <summary>
		/// Specifies the name of the ServiceBus Namespace. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> NamespaceName { get; set; }

		/// <summary>
		/// The Primary Connection String for the ServiceBus Namespace authorization Rule.
		/// </summary>
		public Pulumi.IO<string> PrimaryConnectionString { get; set; }

		/// <summary>
		/// The Primary Key for the ServiceBus Namespace authorization Rule.
		/// </summary>
		public Pulumi.IO<string> PrimaryKey { get; set; }

		/// <summary>
		/// The name of the resource group in which the ServiceBus Namespace exists. Changing this forces a new resource to be created.
		/// </summary>
		public Pulumi.IO<string> ResourceGroupName { get; set; }

		/// <summary>
		/// The Secondary Connection String for the ServiceBus Namespace authorization Rule.
		/// </summary>
		public Pulumi.IO<string> SecondaryConnectionString { get; set; }

		/// <summary>
		/// The Secondary Key for the ServiceBus Namespace authorization Rule.
		/// </summary>
		public Pulumi.IO<string> SecondaryKey { get; set; }

		/// <summary>
		/// Grants send access to this this Authorization Rule. Defaults to `false`.
		/// </summary>
		public Pulumi.IO<bool> Send { get; set; }

		public NamespaceAuthorizationRule(string name, NamespaceAuthorizationRuleArgs args, Pulumi.ResourceOptions opts = default(Pulumi.ResourceOptions))
			: base("azure:eventhub/namespaceAuthorizationRule:NamespaceAuthorizationRule", name, SerialiseArgs(args), opts) {
			Listen = base.Outputs["listen"].Select(item => Protobuf.ToBool(item));
			Manage = base.Outputs["manage"].Select(item => Protobuf.ToBool(item));
			Name = base.Outputs["name"].Select(item => Protobuf.ToString(item));
			NamespaceName = base.Outputs["namespaceName"].Select(item => Protobuf.ToString(item));
			PrimaryConnectionString = base.Outputs["primaryConnectionString"].Select(item => Protobuf.ToString(item));
			PrimaryKey = base.Outputs["primaryKey"].Select(item => Protobuf.ToString(item));
			ResourceGroupName = base.Outputs["resourceGroupName"].Select(item => Protobuf.ToString(item));
			SecondaryConnectionString = base.Outputs["secondaryConnectionString"].Select(item => Protobuf.ToString(item));
			SecondaryKey = base.Outputs["secondaryKey"].Select(item => Protobuf.ToString(item));
			Send = base.Outputs["send"].Select(item => Protobuf.ToBool(item));
		} // ctor

		private static Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>> SerialiseArgs(NamespaceAuthorizationRuleArgs args) {
			var props = new Dictionary<string, Pulumi.IO<Google.Protobuf.WellKnownTypes.Value>>();
			props["listen"] = Protobuf.ToProtobuf(args.Listen);
			props["manage"] = Protobuf.ToProtobuf(args.Manage);
			props["name"] = Protobuf.ToProtobuf(args.Name);
			props["namespaceName"] = Protobuf.ToProtobuf(args.NamespaceName);
			props["resourceGroupName"] = Protobuf.ToProtobuf(args.ResourceGroupName);
			props["send"] = Protobuf.ToProtobuf(args.Send);
			props["primaryConnectionString"] = null; //out
			props["primaryKey"] = null; //out
			props["secondaryConnectionString"] = null; //out
			props["secondaryKey"] = null; //out
			return props;
		} // SerialiseArgs

	} // NamespaceAuthorizationRule
} // Pulumi.Azure.Eventhub
