// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getAnalyticsWorkspace(args: GetAnalyticsWorkspaceArgs, opts?: pulumi.InvokeOptions): Promise<GetAnalyticsWorkspaceResult> {
    return pulumi.runtime.invoke("azure:operationalinsights/getAnalyticsWorkspace:getAnalyticsWorkspace", {
        "name": args.name,
        "resourceGroupName": args.resourceGroupName,
    }, opts);
}

/**
 * A collection of arguments for invoking getAnalyticsWorkspace.
 */
export interface GetAnalyticsWorkspaceArgs {
    readonly name: string;
    readonly resourceGroupName: string;
}

/**
 * A collection of values returned by getAnalyticsWorkspace.
 */
export interface GetAnalyticsWorkspaceResult {
    readonly location: string;
    readonly portalUrl: string;
    readonly primarySharedKey: string;
    readonly retentionInDays: number;
    readonly secondarySharedKey: string;
    readonly sku: string;
    readonly tags: {[key: string]: any};
    readonly workspaceId: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
